Ivysaur 104 the system must be able to get the list of classes that need to be covered from the school schedule and absences tables
ivysaur-unb/on-call-coordinator pull request #27
Opened 2022-11-21 20:27 UTC by uzagmo

2022-11-22 02:06 UTC, camfiander reviewed
Can you put `getClassesToBeCovered.test.js` in `server/routes`? It should be in the same folder as the file it's testing: https://ivysaur.atlassian.net/wiki/spaces/Ivysaur/pages/9535489/Unit+Testing+Best+Practices#Write-tests-using-the-filename-pattern-*filename*.test.js

2022-11-24 15:05 UTC, camfiander requested changes
Left some comments around testing and performance. Overall this is great work but we can definitely improve how we're using prisma to minimize our SQL calls. 

I will try updating the `data-model` branch so it has the changes I mentioned about `ScheduledClass`

2022-11-24 20:01 UTC, uzagmo commented on server/routes/getClassesToBeCovered.test.js
> +    const absences = await getClassesToBeCovered.getAbsences(date);
I don't really have the time to do this right now as I have to work on my current ticket. But I wrote my tests using the data that was created by the initialization scripts so it should be passing.

2022-12-01 04:08 UTC, camfiander approved these changes
Sorry for not approving this sooner, this is good to go

2022-12-01 17:07 UTC, merged